bash run_llama.sh 8 llama_416M_pile_uc_10BT.yaml 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
bash run_llama.sh 8 llama_172M_d_512_l_12_pile_uc_10BT.yaml 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
bash run_llama.sh 8 llama_158M_d_512_l_8_pile_uc_10BT.yaml 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
bash run_llama.sh 8 llama_145M_d_512_l_4_pile_uc_10BT.yaml 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
bash run_llama.sh 8 llama_76M_d_256_l_12_pile_uc_10BT.yaml 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
bash run_llama.sh 8 llama_72M_d_256_l_8_pile_uc_10BT.yaml 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
bash run_llama.sh 8 llama_69M_d_256_l_4_pile_uc_10BT.yaml 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