bash run_mamba.sh 8 mamba_420M.yaml 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
bash run_mamba.sh 8 mamba_172M_d_512_l_24.yaml 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
bash run_mamba.sh 8 mamba_158M_d_512_l_16.yaml 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
bash run_mamba.sh 8 mamba_145M_d_512_l_8.yaml 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
bash run_mamba.sh 8 mamba_76M_d_256_l_24.yaml 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
bash run_mamba.sh 8 mamba_73M_d_256_l_16.yaml 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
bash run_mamba.sh 8 mamba_69M_d_256_l_8.yaml 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