# Template config, need to change dump_dir, data.root_dir and tokenizer.path
# param-count: 75,897,088
dump_dir: /is/cluster/fast/pmayilvahanan/lm_logs/lingua/llama_76M_d_256_l_12_pile_uc_8.4BT/
name: llama_76M
steps: 16_021
probe_freq: null
seed: 777

optim:
  lr: 3e-3
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 256
  n_layers: 12
  n_heads: 8

data:
  root_dir: /fast/smallick/datasets/
  sources:
      pile_uc_shuffled: 1.0
  batch_size: 32
  prefetch_size: 1024
  seq_len: 2048
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: /tmp/tokenizers/original/tokenizer.model

profiling:
  run: true

checkpoint:
  dump:
    every: 191
    keep: 3
  eval:
    every: 191
    keep: -1
  
logging:
  freq: 1

eval:
  harness:
    compute_loss: true
    tasks:
      - hellaswag
      - piqa
      - winogrande
      - arc_easy
      - arc_challenge
      - commonsense_qa
      - openbookqa
      - task: copa
        dataset_kwargs:
          trust_remote_code: true
      - winogrande
      - mmlu
      - task: social_iqa
        dataset_kwargs:
          trust_remote_code: true
  validation:
    use_val_from_train_src: false
    max_steps: 5000
    root_dir: /fast/smallick/datasets/
    sources:
      - c4_shuffled
      - pile_uc_shuffled
      - fineweb_edu_100bt_shuffled
      - refineweb_shuffled
      - slimpajama_shuffled
  generator:
    max_tokens: 16384
    dtype: bf16